sudo: required
services:
  - docker

before_install:
  - docker build -t dbordeleau/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dbordeleau/docker-react npm run test -- --coverage
